/* No magic! */

var PLAYGROUND_HEIGHT = 600;
var PLAYGROUND_WIDTH = 600;

var SNAKES_IN_RING = 24;
var RING_RADIUS = 250;
var SNAKE_RADIUS = 50;	// 1/2 of graphic size

var STARTING_MOVES = 20;
var STARTING_MOVES_LEFT = STARTING_MOVES;
var MIN_COUNT_TO_GET_SPECIAL = 3;
var MIN_COUNT_TO_GET_EXTRAMOVE = 2;
